#micronaut:

#oci:
#  tenant-id: ${ORACLE_CLOUD_TENANT_ID}
#  user-id: ${ORACLE_CLOUD_USER_ID}
#  fingerprint: ${ORACLE_CLOUD_FINGERPRINT}
#  private-key-file: file:${ORACLE_CLOUD_PEM_PATH}
#  region: ${ORACLE_CLOUD_OBJECT_STORAGE_REGION}

oracle-nosql:
  mode: local
  endpoint: "http://localhost:9050/"
  createTables: true
#  compartment: ${ORACLE_CLOUD_COMPARTMENT_ID}
  tables:
    users:
      name: "users_test"
    emails:
      name: "emails_test"
    sessions:
      name: "sessions_test"

## Optional for local testing
#smtp:
#  user: ${EMAIL_USER:}
#  password: ${EMAIL_PASSWORD:}
#
#javamail:
#  properties:
#    mail:
#      smtp:
#        port: 587
#        auth: true
#        starttls:
#          enable: true
#        host: ${EMAIL_HOST:`smtp.email.us-sanjose-1.oci.oraclecloud.com`}
