package app.xivgear.accountsvc.models;

import java.util.List;

public interface UserAccount {
	// col user_id, autogenerated
	int getId();
	// col display_name
	String getDisplayName();
	void setDisplayName(String name);

	// col email
	String getEmail();
	void setEmail(String email);

	// col is_verified
	boolean isVerified();
	void setVerified(boolean verified);

	// col roles
	List<String> getRoles();

	String getPasswordHash();
	void setPasswordHash(String hash);

	boolean verifyEmail(String email, int code);
}
